package io.github.marmer.testutils.annotationprocessing.jpojoassert

import com.google.auto.common.AnnotationMirrors
import com.google.auto.service.AutoService
import java.time.LocalDateTime
import javax.annotation.processing.*
import javax.lang.model.SourceVersion
import javax.lang.model.element.AnnotationMirror
import javax.lang.model.element.Element
import javax.lang.model.element.TypeElement
import javax.tools.Diagnostic
import kotlin.reflect.KClass

@SupportedAnnotationTypes(
    "io.github.marmer.testutils.annotationprocessing.jpojoassert.GenerateAsserter",
    "javax.annotation.processing.Generated"
)
@AutoService(Processor::class)
class AssertionGeneratorProcessor(private val timeProvider: () -> LocalDateTime = LocalDateTime::now) :
    AbstractProcessor() {

    @Synchronized
    override fun init(processingEnvironment: ProcessingEnvironment) = super.init(processingEnvironment)
    override fun process(set: Set<TypeElement>, roundEnvironment: RoundEnvironment): Boolean {
        if (roundEnvironment.processingOver()) {
            return false
        }

        return if (set.contains<GenerateAsserter>()) {
            roundEnvironment.getElementsAnnotatedWith(GenerateAsserter::class.java)
                .forEach { generate(it) }
            true
        } else set.contains<Generated>() &&
                roundEnvironment.existsAnySelfGeneratedSource()
    }

    private fun generate(configurationType: Element) =
        configurationType
            .getAnnotation(GenerateAsserter::class.java)
            .value
            .forEach { qualifiedTypeOrPackageName ->
                generate(qualifiedTypeOrPackageName, configurationType)
            }

    private fun generate(qualifiedTypeOrPackageName: String, configurationType: Element) {
        val baseType = getAllTypeElementsFor(qualifiedTypeOrPackageName)

        if (baseType.isEmpty()) {
            printSkipWarningBecauseOfNotExistingTypeConfigured(configurationType, qualifiedTypeOrPackageName)
        } else {
            baseType.forEach {
                if (it.isAnnotatedWith(Generated::class.java)) {
                    PojoAsserterGenerator(processingEnv, it, timeProvider, javaClass.name).generate()
                } else {
                    printSkipNoteBecauseOfSelfGenerationFor(it)
                }
            }
        }
    }

    private fun getAllTypeElementsFor(qualifiedTypeOrPackageName: String): List<TypeElement> {
        return processingEnv.elementUtils
            .getAllPackageElements(qualifiedTypeOrPackageName)
            .flatMap { it.enclosedElements }
            .map { it as TypeElement } +
                listOf(processingEnv.elementUtils.getTypeElement(qualifiedTypeOrPackageName)).filterNotNull()
    }

    private fun printSkipWarningBecauseOfNotExistingTypeConfigured(
        configurationClass: Element,
        qualifiedTypeOrPackageName: String
    ) {
        configurationClass.getAnnotationMirrors()
            .filter { it.isTypeOf(GenerateAsserter::class) }
            .forEach {
                processingEnv.messager.printMessage(
                    Diagnostic.Kind.MANDATORY_WARNING,
                    "Neither a type nor a type exists for '$qualifiedTypeOrPackageName'",
                    configurationClass,
                    it,
                    AnnotationMirrors.getAnnotationValue(it, "value")
                )
            }
    }

    private fun printSkipNoteBecauseOfSelfGenerationFor(baseType: TypeElement) {
        baseType.getAnnotationMirrors()
            .filter { it.isTypeOf(Generated::class) }
            .forEach {
                processingEnv.messager.printMessage(
                    Diagnostic.Kind.NOTE,
                    "Generation skipped for: '${baseType.qualifiedName}' because is is already generated by this processor",
                    baseType,
                    it,
                    AnnotationMirrors.getAnnotationValue(it, "value")
                )
            }
    }

    private fun RoundEnvironment.existsAnySelfGeneratedSource() =
        getElementsAnnotatedWith(Generated::class.java)
            .any { it.getAnnotation(Generated::class.java).value.contains(this@AssertionGeneratorProcessor.javaClass.name) }


    override fun getSupportedSourceVersion() = SourceVersion.latestSupported()
}

private fun AnnotationMirror.isTypeOf(type: KClass<out Annotation>) =
    annotationType.asElement().toString() == type.qualifiedName


private fun Element.isAnnotatedWith(annotationType: Class<out Annotation>) =
    getAnnotation(annotationType) == null


private inline fun <reified T> Set<TypeElement>.contains() =
    this.find { T::class.qualifiedName == it.qualifiedName.toString() } != null

