name: CI-Build

on: 
  push:
    branches-ignore: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Prepare source directories for sonar
        run: |
          mkdir -p JPojoAssert-processor/src/{main,test}/{java,kotlin}
          mkdir -p JPojoAssert-core/src/{main,test}/{java,kotlin}

      - name: Build
        run: ./mvnw -B clean install -DskipTests

      - name: Test
        run: ./mvnw -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate

      - name: Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B sonar:sonar -am --projects "JPojoAssert-core,JPojoAssert-processor"
#  release:
#    name: Release
#    needs: [build]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Grant execute permission for mvnw
#        run: chmod +x mvnw
#
#      - name: Cache SonarCloud packages
#        uses: actions/cache@v1
#        with:
#          path: ~/.sonar/cache
#          key: ${{ runner.os }}-sonar
#          restore-keys: ${{ runner.os }}-sonar
#
#      - name: Cache Maven packages
#        uses: actions/cache@v1
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#
#      - name: Prepare source directories for sonar
#        run: |
#          mkdir -p JPojoAssert-processor/src/{main,test}/{java,kotlin}
#          mkdir -p JPojoAssert-core/src/{main,test}/{java,kotlin}
#          
# https://github.com/qcastel/github-actions-maven-release
#      - name: Release
#        uses: qcastel/github-actions-maven-release@master
#        with:
#          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
#          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"      
#          gpg-enabled: "true"
#          gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
#          gpg-key: ${{ secrets.GITHUB_GPG_KEY }}
    
